const DEFAULT_PAST_OPERATIONAL_DAYS = 5;
const DEFAULT_FUTURE_OPERATIONAL_DAYS = 1;
const MAX_EDITABLE_OPERATIONAL_DAYS = 3;

module.exports = {
  DEFAULT_PAST_OPERATIONAL_DAYS,
  DEFAULT_FUTURE_OPERATIONAL_DAYS,
  MAX_EDITABLE_OPERATIONAL_DAYS,
};
