const DEFAULT_PAST_OPERATIONAL_DAYS = 5;
const DEFAULT_FUTURE_OPERATIONAL_DAYS = 1;
const MAX_EDITABLE_OPERATIONAL_DAYS = 3;

const REOPEN_TIMEOUT_HOURS = parseInt(process.env.REOPEN_TIMEOUT_HOURS, 10) || 2;

module.exports = {
  DEFAULT_PAST_OPERATIONAL_DAYS,
  DEFAULT_FUTURE_OPERATIONAL_DAYS,
  MAX_EDITABLE_OPERATIONAL_DAYS,
  REOPEN_TIMEOUT_HOURS,
};
