const DEFAULT_PAST_OPERATIONAL_DAYS = 5;
const DEFAULT_FUTURE_OPERATIONAL_DAYS = 1;
const STANDARD_EDIT_WINDOW_DAYS = 3;
const ADMIN_EDIT_WINDOW_DAYS = 5;
const MAX_EDITABLE_OPERATIONAL_DAYS = 5;

module.exports = {
  DEFAULT_PAST_OPERATIONAL_DAYS,
  DEFAULT_FUTURE_OPERATIONAL_DAYS,
  STANDARD_EDIT_WINDOW_DAYS,
  ADMIN_EDIT_WINDOW_DAYS,
  MAX_EDITABLE_OPERATIONAL_DAYS,
};
